Source.cpp
int AIDifficulty
Referenced by setDifficulty, writePath.
int input2
Referenced by setDifficulty, start.
int runCount
Referenced by noNoAreas, start.
int mapWriteCount
Referenced by start, writePath.
int pathSection
Referenced by writePath.
float x
Referenced by start, writePath.
float y
Referenced by start, writePath.
float position
Referenced by start.
float AIPosition
Referenced by start, writePath.
float AIYPosition
float AIXPosition
float DeadZones[100][100]
Referenced by noNoAreas, start, writePath.
float AIPath[20][20]
Referenced by start, writePath.
int nextPath
Referenced by writePath.
string mapInput
Referenced by start.
char input
Referenced by main.
bool XorY
bool added
bool positionDone
Referenced by start, writePath.
bool writePathDone
Referenced by start, writePath.
bool menuDone
Referenced by main, setDifficulty.
bool noNoAreas(float enterZone, int x, int y)
References DeadZones, runCount.
Referenced by start, writePath.
int AIEasyDifficultyPath(int num)
Referenced by writePath.
void AINormalDifficultyPath()
Referenced by writePath.
void AIHardDifficultyPath()
Referenced by writePath.
void writePath()
References AIDifficulty, AIEasyDifficultyPath, AIHardDifficultyPath, AINormalDifficultyPath, AIPath, AIPosition, DeadZones, mapWriteCount, nextPath, noNoAreas, pathSection, positionDone, writePathDone, x, y.
Referenced by start.
void start()
References AIPath, AIPosition, DeadZones, input2, mapInput, mapWriteCount, noNoAreas, position, positionDone, runCount, writePath, writePathDone, x, y.
Referenced by main.
void setDifficulty()
References AIDifficulty, input2, menuDone.
Referenced by main.
void info()
Referenced by main.
int main()
References info, input, menuDone, setDifficulty, start.